---
- name: Install dependencies and start Docker container
  hosts: all
  become: yes

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker image
      docker_image:
        name: apache2
        source: pull

    - name: Start Docker container
      docker_container:
        name: apache_server
        image: apache2
        state: started
        volumes:
          - "/data:/app"
